app = "homeservicesapp-frontend"
primary_region = "ord"
kill_signal = "SIGTERM"
kill_timeout = "5s"

[build]
  dockerfile = "Dockerfile"

[env]
  # Environment will be set via secrets in CI/CD
  NODE_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = "requests"
    hard_limit = 100
    soft_limit = 50

  [[http_service.checks]]
    interval = "30s"
    grace_period = "10s"
    method = "get"
    path = "/health"
    protocol = "http"
    timeout = "5s"
    headers = {}

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[[statics]]
  guest_path = "/usr/share/nginx/html"
  url_prefix = "/"

# Auto-scaling configuration
[scaling]
  min_machines_running = 0
  max_machines_running = 3

# Restart policy
[restart]
  policy = "on-failure"

# Metrics
[metrics]
  port = 8080
  path = "/health"