version: '3.8'

services:
  # API Service
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - Database__Provider=Sqlite
      - ConnectionStrings__Default=Data Source=/data/app.db
      - App__CorsOrigins=http://localhost:3000,http://localhost:5173
      - App__SelfUrl=http://localhost:8080
      - AuthServer__Authority=http://authserver:8081
      - AuthServer__RequireHttpsMetadata=false
    volumes:
      - api-data:/data
    networks:
      - hsapp-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Auth Server
  authserver:
    build:
      context: ./backend
      dockerfile: AuthServer.Dockerfile
    ports:
      - "8081:8081"
    environment:
      - Database__Provider=Sqlite
      - ConnectionStrings__Default=Data Source=/data/auth.db
      - App__CorsOrigins=http://localhost:3000,http://localhost:5173
      - App__SelfUrl=http://localhost:8081
      - App__ClientUrl=http://localhost:3000
      - App__RedirectAllowedUrls=http://localhost:3000,http://localhost:5173
    volumes:
      - auth-data:/data
    networks:
      - hsapp-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=http://localhost:8080/api
        - VITE_API_HOST_URL=http://localhost:8080/api
        - VITE_AUTH_API_BASE_URL=http://localhost:8080/api
    ports:
      - "3000:8080"
    networks:
      - hsapp-network
    depends_on:
      - api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  hsapp-network:
    driver: bridge

volumes:
  api-data:
  auth-data: