services:
  - type: web
    name: homeservices-api
    env: docker
    plan: free
    dockerfilePath: backend/Dockerfile
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: Database__Provider
        value: PostgreSql
      - key: ConnectionStrings__Default
        fromSecret: PG_CONN_STR
      - key: App__CorsOrigins
        fromSecret: APP_CORS_ORIGINS

  - type: web
    name: homeservices-auth
    env: docker
    plan: free
    dockerfilePath: backend/AuthServer.Dockerfile
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: Database__Provider
        value: PostgreSql
      - key: ConnectionStrings__Default
        fromSecret: PG_CONN_STR
      - key: App__SelfUrl
        fromSecret: AUTH_SELF_URL
      - key: App__ClientUrl
        fromSecret: AUTH_CLIENT_URL
      - key: App__CorsOrigins
        fromSecret: AUTH_CORS_ORIGINS