app = "homeservicesapp-auth"
primary_region = "ord"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  dockerfile = "AuthServer.Dockerfile"

[env]
  ASPNETCORE_URLS = "http://0.0.0.0:8081"
  ConnectionStrings__Default = "Data Source=/data/HomeServicesApp.db"
  App__SelfUrl = "https://<your-auth-domain>"
  App__ClientUrl = "https://<your-gh-username>.github.io/<repo>"
  App__CorsOrigins = "https://<your-gh-username>.github.io,https://<your-gh-username>.github.io/<repo>,https://homeservicesapp-frontend.fly.dev"

[[services]]
  internal_port = 8081
  processes = ["app"]
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "requests"
    hard_limit = 50
    soft_limit = 25

[[mounts]]
  source = "data"
  destination = "/data"