app = "homeservicesapp-auth"
primary_region = "iad"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  dockerfile = "Dockerfile.auth"

[env]
  ASPNETCORE_URLS = "http://0.0.0.0:8081"
  # Neon PostgreSQL connection string
  ConnectionStrings__Default = "Host=ep-sweet-king-aephthql-pooler.c-2.us-east-2.aws.neon.tech;Port=5432;Database=neondb;Username=neondb_owner;Password=npg_9JPzYQVlw5Ik;SSL Mode=Require;"
  Database__Provider = "PostgreSql"
  App__SelfUrl = "https://<your-auth-domain>"
  App__ClientUrl = "https://<your-gh-username>.github.io/<repo>"
  App__CorsOrigins = "https://<your-gh-username>.github.io,https://<your-gh-username>.github.io/<repo>,https://homeservicesapp-frontend.fly.dev"

[[services]]
  internal_port = 8081
  processes = ["app"]
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "requests"
    hard_limit = 50
    soft_limit = 25

[http_service]
  internal_port = 8081
  force_https = true

  [[http_service.checks]]
    interval = "10s"
    grace_period = "5s"
    method = "GET"
    path = "/health"
    protocol = "http"
    timeout = "2s"

# Secrets for production (set via `fly secrets set`)
# ConnectionStrings__Default="Host=ep-sweet-king-aephthql-pooler.c-2.us-east-2.aws.neon.tech;Port=5432;Database=neondb;Username=neondb_owner;Password=npg_9JPzYQVlw5Ik;SSL Mode=Require;"
# Database__Provider="PostgreSql"