app = "homeservicesapp-api"
primary_region = "iad"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  dockerfile = "Dockerfile"

[env]
  ASPNETCORE_URLS = "http://0.0.0.0:8080"
  # Neon PostgreSQL connection string
  ConnectionStrings__Default = "Host=ep-sweet-king-aephthql-pooler.c-2.us-east-2.aws.neon.tech;Port=5432;Database=neondb;Username=neondb_owner;Password=npg_9JPzYQVlw5Ik;SSL Mode=Require;"
  Database__Provider = "PostgreSql"
  # Set this from your frontend deploy URL(s) to enable CORS
  App__CorsOrigins = "https://<your-gh-username>.github.io,https://<your-gh-username>.github.io/<repo>,https://homeservicesapp-frontend.fly.dev"

[http_service]
  internal_port = 8080
  force_https = true

  [[http_service.checks]]
    interval = "10s"
    grace_period = "5s"
    method = "GET"
    path = "/health"
    protocol = "http"
    timeout = "2s"

# Secrets for production (set via `fly secrets set`)
# ConnectionStrings__Default="Host=ep-sweet-king-aephthql-pooler.c-2.us-east-2.aws.neon.tech;Port=5432;Database=neondb;Username=neondb_owner;Password=npg_9JPzYQVlw5Ik;SSL Mode=Require;"
# Database__Provider="PostgreSql"