app = "homeservicesapp-api"
primary_region = "ord"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  dockerfile = "Dockerfile"

[env]
  ASPNETCORE_URLS = "http://0.0.0.0:8080"
  # Default to sqlite at /data; override in secrets if needed
  ConnectionStrings__Default = "Data Source=/data/HomeServicesApp.db"
  # Set this from your frontend deploy URL(s) to enable CORS
  App__CorsOrigins = "https://<your-gh-username>.github.io,https://<your-gh-username>.github.io/<repo>"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "requests"
    hard_limit = 50
    soft_limit = 25

  [[services.http_checks]]
    interval = "15s"
    grace_period = "30s"
    method = "get"
    path = "/swagger"
    protocol = "http"
    timeout = "10s"

[metrics]
  port = 8080
  path = "/metrics"

[[mounts]]
  source = "data"
  destination = "/data"