name: Deploy AuthServer to Fly.io

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/auth-fly-deploy.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Ensure app and volume exist
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          APP_NAME="${{ vars.FLY_APP_NAME_AUTH }}"
          REGION="${{ vars.FLY_REGION }}"
          if [ -z "$APP_NAME" ]; then APP_NAME="homeservicesapp-auth"; fi
          if [ -z "$REGION" ]; then REGION="ord"; fi
          echo "Using app=$APP_NAME region=$REGION"
          flyctl apps list | grep -q "^${APP_NAME}\b" || flyctl apps create "${APP_NAME}"
          flyctl volumes list --app "${APP_NAME}" | grep -q "\bdata\b" || flyctl volumes create data --app "${APP_NAME}" --region "${REGION}" --size 1

      - name: Set environment secrets (URLs and CORS)
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          APP_NAME="${{ vars.FLY_APP_NAME_AUTH }}"
          SELF_URL="${{ vars.AUTH_SELF_URL }}"
          CLIENT_URL="${{ vars.AUTH_CLIENT_URL }}"
          CORS="${{ vars.AUTH_CORS_ORIGINS }}"
          if [ -z "$APP_NAME" ]; then APP_NAME="homeservicesapp-auth"; fi
          if [ -n "$SELF_URL" ]; then flyctl secrets set App__SelfUrl="$SELF_URL" --app "$APP_NAME" --stage; fi
          if [ -n "$CLIENT_URL" ]; then flyctl secrets set App__ClientUrl="$CLIENT_URL" --app "$APP_NAME" --stage; fi
          if [ -n "$CORS" ]; then flyctl secrets set App__CorsOrigins="$CORS" --app "$APP_NAME" --stage; fi

      - name: Deploy to Fly (AuthServer)
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          APP_NAME="${{ vars.FLY_APP_NAME_AUTH }}"
          if [ -z "$APP_NAME" ]; then APP_NAME="homeservicesapp-auth"; fi
          flyctl deploy --config fly-auth.toml --app "$APP_NAME" --remote-only --auto-confirm