name: Deploy AuthServer to Fly.io

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/auth-fly-deploy.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Ensure app and volume exist
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl apps list | grep -q "^homeservicesapp-auth\b" || flyctl apps create homeservicesapp-auth
          flyctl volumes list --app homeservicesapp-auth | grep -q "\bdata\b" || flyctl volumes create data --app homeservicesapp-auth --region ord --size 1

      - name: Deploy to Fly (AuthServer)
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl deploy --config fly-auth.toml --remote-only --auto-confirm