name: Azure Destroy Resources

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "DESTROY" to confirm deletion'
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Validate Confirmation
        if: github.event.inputs.confirm != 'DESTROY'
        run: |
          echo "❌ Destruction cancelled. You must type 'DESTROY' to confirm."
          exit 1
      
      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Delete Resource Group
        env:
          RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP || secrets.AZ_RESOURCE_GROUP }}
        run: |
          echo "⚠️  Deleting resource group: $RESOURCE_GROUP"
          az group delete -n $RESOURCE_GROUP --yes --no-wait
          echo "✅ Deletion initiated. Resources will be removed in the background."