name: Deploy Backend to Koyeb

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/koyeb-deploy.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and authenticate Koyeb CLI
        uses: koyeb-community/koyeb-actions@v2
        with:
          api_token: ${{ secrets.KOYEB_API_TOKEN }}

      - name: Determine settings
        id: vars
        run: |
          APP_NAME="${{ vars.KOYEB_APP_NAME }}"
          if [ -z "$APP_NAME" ]; then APP_NAME="homeservices-app"; fi
          API_SERVICE="${{ vars.KOYEB_SERVICE_API }}"
          if [ -z "$API_SERVICE" ]; then API_SERVICE="homeservices-api"; fi
          AUTH_SERVICE="${{ vars.KOYEB_SERVICE_AUTH }}"
          if [ -z "$AUTH_SERVICE" ]; then AUTH_SERVICE="homeservices-auth"; fi

          # Derive repo URL and branch for Koyeb git builder
          REPO_URL="https://github.com/${{ github.repository }}"
          BRANCH="${{ github.ref_name }}"

          echo "app_name=$APP_NAME" >> $GITHUB_OUTPUT
          echo "api_service=$API_SERVICE" >> $GITHUB_OUTPUT
          echo "auth_service=$AUTH_SERVICE" >> $GITHUB_OUTPUT
          echo "repo_url=$REPO_URL" >> $GITHUB_OUTPUT
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT

      - name: Deploy API to Koyeb
        uses: koyeb/action-git-deploy@v1
        with:
          token: ${{ secrets.KOYEB_API_TOKEN }}
          app-name: ${{ steps.vars.outputs.app_name }}
          service-name: ${{ steps.vars.outputs.api_service }}
          service-type: web
          git-branch: ${{ steps.vars.outputs.branch }}
          git-path: backend
          builder: dockerfile
          dockerfile: Dockerfile
          service-ports: 8080:http
          service-routes: /:8080
          service-healthcheck-path: /
          instance-type: nano
          scaling: 1
          service-env: |
            Database__Provider=Sqlite
            ConnectionStrings__Default=Data Source=/data/app.db

      - name: Deploy Auth to Koyeb
        uses: koyeb/action-git-deploy@v1
        with:
          token: ${{ secrets.KOYEB_API_TOKEN }}
          app-name: ${{ steps.vars.outputs.app_name }}
          service-name: ${{ steps.vars.outputs.auth_service }}
          service-type: web
          git-branch: ${{ steps.vars.outputs.branch }}
          git-path: backend
          builder: dockerfile
          dockerfile: AuthServer.Dockerfile
          service-ports: 8081:http
          service-routes: /:8081
          service-healthcheck-path: /
          instance-type: nano
          scaling: 1
          service-env: |
            Database__Provider=Sqlite
            ConnectionStrings__Default=Data Source=/app/auth.db

      - name: Output URLs
        run: |
          echo "Koyeb App: https://app.koyeb.com/apps/${{ steps.vars.outputs.app_name }}"